### PR TITLE
Update Playwright driver to 1.41.0

### PR DESCRIPTION
**Pull request by YusukeIwaki**

### CODE REVIEW

**Comment by mhenrixon** [comment]
Will you be releasing this as well? I checked the https://rubygems.org/gems/playwright-ruby-client but it isn't released yet.

**Comment by mhenrixon** [comment]
@YusukeIwaki any plans on cutting a new gem version? You created a release on GitHub but never to RubyGems.

**Comment by YusukeIwaki** [comment]
@mhenrixon Sorry for my mistake, https://github.com/YusukeIwaki/playwright-ruby-client/actions/runs/7654882896/job/20859759674
I will re-deploy it. Thank you.

**Comment by YusukeIwaki** [comment]
https://rubygems.org/gems/playwright-ruby-client/versions/1.41.0

**Pull request merged**
